#!/bin/bash

docker exec -it reactjs cd /app && npm install && npm run build
docker exec -it reactjs cp -Rf /app/build/. /var/www/html
docker exec -it reactjs systemctl enable httpd
docker exec -it reactjs systemctl start httpd
